language: java
jdk: oraclejdk11
os: linux
dist: precise

addons:
  sonarcloud:
    organization: "xcesco"
    token: $SONAR_TOKEN

after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=xcesco_power-trainer